---
- name: Crear usuario ansible en el sistema linux y puede hacer sudo.
  hosts: all
  gather_facts: false
  tasks:
  - name: Seteamos la clave  
    set_fact:
     user_password: 'ansible'

  - name: Add the user 'ansible' en grupo 'wheel'
    user:
      name: ansible
      comment: Ansible User
      groups: wheel
      password: "{{ user_password | password_hash('sha512', 'ansible') }}"
