---
- name: Start services, if not started
  hosts: "{{ var_nodo }}"
  tasks:
  - name: Start service firewalld, if no started  
    service:
     name: firewalld
     state: restarted
     enabled: yes
