---
- name: Subscription Manager
  gather_facts: false
  hosts: "{{ var_nodo }}"
  tasks:
   - name: Register as user with password and auto-subscribe to available content.
     redhat_subscription:
      state: present
      username: "{{ rhn_user }}"
      password: "{{ rhn_password }}"
      auto_attach: true
