---
- name: Deploy WebApp en el host/grupo "{{ var_nodo }}".
  hosts: "{{ var_nodo }}"
  gather_facts: false
  tasks:
  - name: Pull file from source
    git:
     repo: "{{ var_repo }}"
     dest: /var/www/html
     version: "{{ var_version }}"
