---
- name: Telegram Notifications
  hosts: localhost
  tasks:
  - name: enviar mensaje via Telegram
    telegram:
     token: '1291052384:AAEFHpnvwdV3YsYpOmnz1szVlAL1GZOq60I'
     chat_id: 756926933
     msg: Tarea Ansible Finalizada Satisfactoriamente el {{ansible_date_time.date}} por {{ tower_user_name }} 
